./clapton joise.txt ltim.nes ltim.nes
./clapton hoise.txt ltim.nes ltim.nes
./clapton zoise.txt ltim.nes ltim.nes
./clapton soise.txt ltim.nes ltim.nes
./clapton ooise.txt ltim.nes ltim.nes
./clapton woise.txt ltim.nes ltim.nes
./clapton choise.txt ltim.nes ltim.nes
./clapton might.txt ltim.nes ltim.nes
./clapton coise.txt ltim.nes ltim.nes
./clapton qoise.txt ltim.nes ltim.nes
./clapton doise.txt ltim.nes ltim.nes
./clapton loise.txt ltim.nes ltim.nes
./clapton loise_end2.txt ltim.nes ltim.nes
./clapton joise_end.txt ltim.nes ltim.nes
./clapton joise_end2.txt ltim.nes ltim.nes
./clapton joise_bank14.txt ltim.nes ltim.nes
./clapton ghost.txt ltim.nes ltim.nes
./clapton ghost_lv2.txt ltim.nes ltim.nes
./clapton ghost_lv3.txt ltim.nes ltim.nes
./clapton ghost_lv4.txt ltim.nes ltim.nes
./clapton ghost_lv5.txt ltim.nes ltim.nes
./clapton ghost_lv6.txt ltim.nes ltim.nes
./clapton ghost_lv7.txt ltim.nes ltim.nes
./clapton ghost_lv9.txt ltim.nes ltim.nes
./clapton jhoust.txt ltim.nes ltim.nes
